/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import company.project.Tools;
import entity.Employee;
import entity.Employee_Phones;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mohamed
 */
public class employee extends javax.swing.JFrame {

    /**
     * Creates new form employee
     */
    public employee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        hire = new com.toedter.calendar.JDateChooser();
        birth = new com.toedter.calendar.JDateChooser();
        empID = new control.JTextBox(15);
        empname = new control.JTextBox(15);
        empadd = new control.JTextBox(15);
        empsalary = new control.JTextBox(15);
        del = new control.JMyButton();
        back = new control.JMyButton();
        find = new control.JMyButton();
        select = new control.JMyButton();
        clear = new control.JMyButton();
        add = new control.JMyButton();
        up = new control.JMyButton();
        jLabel8 = new javax.swing.JLabel();
        radID = new javax.swing.JRadioButton();
        radname = new javax.swing.JRadioButton();
        radadd = new javax.swing.JRadioButton();
        radsalary = new javax.swing.JRadioButton();
        radhire = new javax.swing.JRadioButton();
        radbirth = new javax.swing.JRadioButton();
        txtsearch = new control.JTextBox(15);
        search = new control.JMyButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        cmx = new control.JMyCompo();
        radDep = new javax.swing.JRadioButton();
        addDept = new control.JMyButton();
        jLabel10 = new javax.swing.JLabel();
        empPhone = new control.JTextBox(15);
        addPhone = new control.JMyButton();
        remove = new control.JMyButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPhones = new javax.swing.JTable();
        radphone = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 32)); // NOI18N
        jLabel1.setText("Employees");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Employee ID :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Employee Name :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Employee Address :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Employee Salary :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Hiring Date :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Birth Date :");

        hire.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                hireKeyPressed(evt);
            }
        });

        birth.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                birthKeyPressed(evt);
            }
        });

        empID.setEditable(false);
        empID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        empname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        empname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                empnameKeyPressed(evt);
            }
        });

        empadd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        empadd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                empaddKeyPressed(evt);
            }
        });

        empsalary.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        empsalary.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                empsalaryKeyPressed(evt);
            }
        });

        del.setText("Delete");
        del.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delActionPerformed(evt);
            }
        });

        back.setText("Back");
        back.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        find.setText("Find");
        find.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findActionPerformed(evt);
            }
        });

        select.setText("Display All");
        select.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        select.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectActionPerformed(evt);
            }
        });

        clear.setText("Clear");
        clear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        add.setText("Add");
        add.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        up.setText("Update");
        up.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Search By :");

        radID.setBackground(new java.awt.Color(255, 255, 255));
        radID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        radID.setText("ID");

        radname.setBackground(new java.awt.Color(255, 255, 255));
        radname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        radname.setText("Name");

        radadd.setBackground(new java.awt.Color(255, 255, 255));
        radadd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        radadd.setText("Address");

        radsalary.setBackground(new java.awt.Color(255, 255, 255));
        radsalary.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        radsalary.setText("Salary");

        radhire.setBackground(new java.awt.Color(255, 255, 255));
        radhire.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        radhire.setText("Hiring");

        radbirth.setBackground(new java.awt.Color(255, 255, 255));
        radbirth.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        radbirth.setText("Birth");

        txtsearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtsearchKeyPressed(evt);
            }
        });

        search.setText("Search");
        search.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee ID", "Employee Name", "Employee Address", "Employee Salary", "Hiring Date", "Birth Date", "Department ID", "Department Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMouseClicked(evt);
            }
        });
        tbl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbl);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Department :");

        cmx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmxActionPerformed(evt);
            }
        });
        cmx.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmxKeyPressed(evt);
            }
        });

        radDep.setBackground(new java.awt.Color(255, 255, 255));
        radDep.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        radDep.setText("Department");

        addDept.setText("Add new");
        addDept.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addDept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDeptActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Phone :");

        empPhone.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        empPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                empPhoneKeyPressed(evt);
            }
        });

        addPhone.setText("Add new");
        addPhone.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPhoneActionPerformed(evt);
            }
        });

        remove.setText("Remove");
        remove.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeActionPerformed(evt);
            }
        });

        tblPhones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Phones"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblPhones);

        radphone.setBackground(new java.awt.Color(255, 255, 255));
        radphone.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        radphone.setText("Phones");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel5)))
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(hire, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                                        .addComponent(empsalary, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(birth, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(empID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(empadd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(empname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmx, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(empPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(addPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(addDept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(remove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10))
                    .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(find, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(select, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(up, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(del, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 783, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(533, 533, 533)
                                .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(189, 189, 189)
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(radID)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(radname)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(radadd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(radsalary)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(radhire)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(radbirth)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(radDep)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(radphone)))
                        .addGap(9, 9, 9))))
            .addGroup(layout.createSequentialGroup()
                .addGap(600, 600, 600)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(radID)
                            .addComponent(radname)
                            .addComponent(radadd)
                            .addComponent(radsalary)
                            .addComponent(radhire)
                            .addComponent(radbirth)
                            .addComponent(radDep)
                            .addComponent(radphone))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(empID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(empname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(empadd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(empsalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(hire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(birth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(cmx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addDept, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(empPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(remove, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(del, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(up, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(find, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(select, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delActionPerformed
        // TODO add your handling code here:
        delete();
    }//GEN-LAST:event_delActionPerformed

    Employee emp = new Employee();

    private void clear() {
        Tools.clear(this);
        //txtID.requestFocus();
        empID.setText(emp.getAutoNumber());
        add.setEnabled(true);
        up.setEnabled(false);
        del.setEnabled(false);
        removeActionPerformed(null);
        empname.requestFocus();
    }

    private void sets() {
        SimpleDateFormat f = new SimpleDateFormat("yyyy-MM-dd");            //format of date
        String Hire = String.valueOf(f.format(hire.getDate()));
        String Birth = String.valueOf(f.format(birth.getDate()));
        String DName = cmx.getSelectedItem().toString();
        String DNO = dep.DP.getValueByName(DName);

        emp.setEmpNO(Integer.parseInt(empID.getText()));
        emp.setEmpName(empname.getText());
        emp.setAddress(empadd.getText());
        emp.setSalary(Double.parseDouble(empsalary.getText()));
        emp.setHiringDate(Hire);
        emp.setBirthdate(Birth);
        emp.setDeptNO(Integer.parseInt(DNO));
    }


    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        mainfrm mf = new mainfrm();
        mf.setTitle("Main Menu");
        this.dispose();
        Tools.open(mf);
    }//GEN-LAST:event_backActionPerformed

    private void findActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findActionPerformed
        // TODO add your handling code here:
        String strID = (String) Tools.InputBox("Enter The ID of Employee:");
        emp.setEmpNO(Integer.parseInt(strID));
        emp.selectOneRow(tbl);
    }//GEN-LAST:event_findActionPerformed

    private void selectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectActionPerformed
        // TODO add your handling code here:
        emp.selectAll(tbl);
    }//GEN-LAST:event_selectActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        clear();
        emp.selectAll(tbl);
    }//GEN-LAST:event_clearActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        add();
    }//GEN-LAST:event_addActionPerformed

    private void delete() {
        if (Tools.ConfirmMsg("Are You Sure You Want to Delete this Item ?")) {
            ep.setEmpNO(Integer.parseInt(empID.getText()));
            ep.deleteAllPhonesByEmp();
            
            sets();
            emp.delete();
            
            clear();
            emp.selectAll(tbl);
        }
    }
    Employee_Phones ep = new Employee_Phones();
    private void add() {
        sets();
        emp.add();
        
        //add phones here
        ep.setEmpNO(Integer.parseInt(empID.getText()));
        for (int i=0;i<tblPhones.getRowCount();i++) {
            ep.setPhone(tblPhones.getValueAt(i, 0).toString());
            ep.add();
        }
        clear();
        emp.selectAll(tbl);
    }
    private void update() {
        sets();
        emp.update();
        
        ep.setEmpNO(Integer.parseInt(empID.getText()));
        //delete all phones for this employee
        ep.deleteAllPhonesByEmp();
        //add phones again for this employee
        for (int i=0;i<tblPhones.getRowCount();i++) {
            ep.setPhone(tblPhones.getValueAt(i, 0).toString());
            ep.add();
        }
        
        clear();
        emp.selectAll(tbl);
    }
    private void upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upActionPerformed
        // TODO add your handling code here:
        update();
    }//GEN-LAST:event_upActionPerformed

    private String mylike(){
        return " like '%"+txtsearch.getText()+"%'";
    }
    private void search (){
        String test; 
        String searchquery = "select * from employee_data where ";
        if (radID.isSelected()) {
            test = Tools.getnum(txtsearch.getText());
            searchquery+= "Employee_ID"+mylike();
        } else if (radname.isSelected()) {
            test = Tools.removenum(txtsearch.getText());
            searchquery += "Name"+mylike();
        } else if (radadd.isSelected()) {
            searchquery += "Address"+mylike();
        } else if (radsalary.isSelected()) {
            test = Tools.removenum(txtsearch.getText());
            searchquery += "Salary"+mylike();
        } else if (radhire.isSelected()) {
            test = Tools.getnum(txtsearch.getText());
            searchquery += "Hire_Date"+mylike();
        } else if (radbirth.isSelected()) {
            test = Tools.getnum(txtsearch.getText());
            searchquery += "Birthday_Date"+mylike();
        } else if (radDep.isSelected()){
            searchquery += "Department_ID"+mylike()+" or Department"+mylike();
        } else {
            String str = ep.getEmpByPhone(txtsearch.getText());
            searchquery += "Employee_ID like '%"+str+"%'";
        }
        emp.getCustom(searchquery, tbl);
        if (tbl.getRowCount()<=0) {
                Tools.msg("Can't Find any information");
                emp.selectAll(tbl);
                txtsearch.setText("");
            }
    }
    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        search();
    }//GEN-LAST:event_searchActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        btngroup.add(radID);
        btngroup.add(radname);
        btngroup.add(radadd);
        btngroup.add(radsalary);
        btngroup.add(radhire);
        btngroup.add(radbirth);
        btngroup.add(radDep);
        btngroup.add(radphone);
        clear();
        emp.selectAll(tbl);
        tbl.getTableHeader().setReorderingAllowed(false);
        tblPhones.getTableHeader().setReorderingAllowed(false);
        db.database.FillCombo("department", "DeptName", cmx);
    }//GEN-LAST:event_formWindowOpened

    department dep = new department();

    private void tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMouseClicked
        // TODO add your handling code here:
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            int row = tbl.getSelectedRow();
            empID.setText(tbl.getValueAt(row, 0).toString());
            empname.setText(tbl.getValueAt(row, 1).toString());
            empadd.setText(tbl.getValueAt(row, 2).toString());
            empsalary.setText(tbl.getValueAt(row, 3).toString());
            Date hdate = sdf.parse(tbl.getValueAt(row, 4).toString());
            Date bdate = sdf.parse(tbl.getValueAt(row, 5).toString());
            hire.setDate(hdate);
            birth.setDate(bdate);
            cmx.setSelectedItem(tbl.getValueAt(row, 7));

            ep.setEmpNO(Integer.parseInt(empID.getText()));
            ep.selectAll(tblPhones);
            
            add.setEnabled(false);
            up.setEnabled(true);
            del.setEnabled(true);
        } catch (Exception ex) {
            Tools.msg(ex.getMessage());
        }
    }//GEN-LAST:event_tblMouseClicked

    private void addDeptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDeptActionPerformed
        // TODO add your handling code here:'
        int DepNO = Integer.parseInt(dep.DP.getAutoNumber());
        String DepName = (String) Tools.InputBox("Enter Department Name :");
        String DepLoc = (String) Tools.InputBox("Enter Department Location :");
        
        if ("".equals(DepName) || "".equals(DepLoc)) {
            Tools.msg("Can't Save Department as value null");
        }
        else {
        dep.DP.setDeptNO(DepNO);
        dep.DP.setDeptName(DepName);
        dep.DP.setLocation(DepLoc);
        dep.DP.add();
        db.database.FillCombo("department", "DeptName", cmx);
        }
    }//GEN-LAST:event_addDeptActionPerformed

    private void tblKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_DELETE){
            delete();
        }
    }//GEN-LAST:event_tblKeyPressed

    private void cmxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmxKeyPressed
        // TODO add your handling code here:
        if (add.isEnabled()) {
            if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
                add();
            }
        } else if (up.isEnabled()){
            if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
                update();
            }
        }
    }//GEN-LAST:event_cmxKeyPressed

    private void birthKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_birthKeyPressed
        // TODO add your handling code here:
        if (up.isEnabled()) {
            if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
                update();
            }
        }
    }//GEN-LAST:event_birthKeyPressed

    private void hireKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hireKeyPressed
        // TODO add your handling code here:
        if (up.isEnabled()) {
            if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
                update();
            }
        }
    }//GEN-LAST:event_hireKeyPressed

    private void empsalaryKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_empsalaryKeyPressed
        // TODO add your handling code here:
        if (up.isEnabled()) {
            if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
                update();
            }
        }
    }//GEN-LAST:event_empsalaryKeyPressed

    private void empaddKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_empaddKeyPressed
        // TODO add your handling code here:
        if (up.isEnabled()) {
            if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
                update();
            }
        }
    }//GEN-LAST:event_empaddKeyPressed

    private void empnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_empnameKeyPressed
        // TODO add your handling code here:
        if (up.isEnabled()) {
            if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
                update();
            }
        }
    }//GEN-LAST:event_empnameKeyPressed

    private void txtsearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            search();
        }
    }//GEN-LAST:event_txtsearchKeyPressed

    private void empPhoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_empPhoneKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            addPhones();
        }
    }//GEN-LAST:event_empPhoneKeyPressed

    private void addPhones(){
        DefaultTableModel model = (DefaultTableModel) tblPhones.getModel();
        model.addRow(new Object [] {empPhone.getText()});
        empPhone.setText(null);
        empPhone.requestFocus();
    }
    
    private void removePhones(){
        DefaultTableModel model = (DefaultTableModel) tblPhones.getModel();
        model.setNumRows((0));
    }
    
    private void addPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPhoneActionPerformed
        // TODO add your handling code here:
        addPhones();
    }//GEN-LAST:event_addPhoneActionPerformed

    private void removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeActionPerformed
        // TODO add your handling code here:
        removePhones();
    }//GEN-LAST:event_removeActionPerformed

    private void cmxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new employee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private control.JMyButton add;
    private control.JMyButton addDept;
    private control.JMyButton addPhone;
    private control.JMyButton back;
    private com.toedter.calendar.JDateChooser birth;
    private javax.swing.ButtonGroup btngroup;
    private control.JMyButton clear;
    private control.JMyCompo cmx;
    private control.JMyButton del;
    private javax.swing.JTextField empID;
    private javax.swing.JTextField empPhone;
    private javax.swing.JTextField empadd;
    private javax.swing.JTextField empname;
    private javax.swing.JTextField empsalary;
    private control.JMyButton find;
    private com.toedter.calendar.JDateChooser hire;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton radDep;
    private javax.swing.JRadioButton radID;
    private javax.swing.JRadioButton radadd;
    private javax.swing.JRadioButton radbirth;
    private javax.swing.JRadioButton radhire;
    private javax.swing.JRadioButton radname;
    private javax.swing.JRadioButton radphone;
    private javax.swing.JRadioButton radsalary;
    private control.JMyButton remove;
    private control.JMyButton search;
    private control.JMyButton select;
    private javax.swing.JTable tbl;
    private javax.swing.JTable tblPhones;
    private javax.swing.JTextField txtsearch;
    private control.JMyButton up;
    // End of variables declaration//GEN-END:variables
}
